try {
    consol.log('a'/2);
} catch (err) {
    console.log('error');
}